# Generated by Django 4.1.3 on 2022-11-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_image',
            field=models.ImageField(upload_to='media', verbose_name='Фото'),
        ),
    ]
