# Generated by Django 4.1.3 on 2022-11-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0002_alter_ads_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
