# Generated by Django 4.1.3 on 2022-11-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0005_alter_ads_ad_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_discription',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описания реклама'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_social',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Соц. сети'),
        ),
    ]
