# Generated by Django 4.1.3 on 2022-11-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0006_alter_ads_ad_discription_alter_ads_ad_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
