# Generated by Django 4.1.3 on 2022-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0008_alter_ads_ad_client_alter_ads_ad_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_client',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_discription',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описания реклама'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_social',
            field=models.CharField(blank=True, max_length=20, verbose_name='Соц. сети'),
        ),
    ]
