# Generated by Django 4.1.3 on 2022-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0009_alter_ads_ad_client_alter_ads_ad_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_client',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_discription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_social',
            field=models.CharField(max_length=20),
        ),
    ]
