# Generated by Django 4.1.3 on 2022-11-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0012_adskarasuu_delete_ads_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adskarasuu',
            options={},
        ),
        migrations.RemoveField(
            model_name='adskarasuu',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='adskarasuu',
            name='number',
        ),
        migrations.RemoveField(
            model_name='adskarasuu',
            name='social',
        ),
        migrations.AlterModelTable(
            name='adskarasuu',
            table=None,
        ),
    ]
