# Generated by Django 4.1.3 on 2022-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0013_alter_adskarasuu_options_remove_adskarasuu_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adskarasuu',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adskarasuu',
            name='discription',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
