# Generated by Django 4.1.3 on 2022-11-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0014_alter_adskarasuu_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AdsKarasuu',
        ),
    ]
