# Generated by Django 4.1.3 on 2022-11-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0016_rename_author_ads_name_rename_title_ads_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(default=True, upload_to='media'),
        ),
    ]
